from __future__ import annotations

from pathlib import Path
from edge_agent_scanner.harness.planner import HarnessPlan


def _docker_safe_start_command(cmd: str | None) -> str | None:
    if not cmd:
        return cmd
    # Apps inside Docker must bind to 0.0.0.0 for host port mapping to work.
    return (
        cmd.replace("--host 127.0.0.1", "--host 0.0.0.0")
        .replace("--host localhost", "--host 0.0.0.0")
        .replace("127.0.0.1:8000", "0.0.0.0:8000")
        .replace("localhost:8000", "0.0.0.0:8000")
    )


def write_evals_yaml(repo_path: Path, plan: HarnessPlan) -> Path:
    d = repo_path / ".edgeagent"
    d.mkdir(parents=True, exist_ok=True)
    out = d / "evals.yaml"

    chat_url = plan.candidate_chat_urls[0] if plan.candidate_chat_urls else "http://127.0.0.1:8000/chat"
    start_command = _docker_safe_start_command(plan.start_command)

    content = f"""# Auto-generated by Edge Agent AI. Review before running.
app:
  kind: "http"
  install_command: {repr(plan.install_command)}
  start_command: {repr(start_command)}
  health_url: null
  chat_url: {repr(chat_url)}
  method: "POST"
  input_template:
    message: "{{{{prompt}}}}"
  output_path: "response"

sandbox:
  # Use bridge for HTTP tests. "none" blocks port-mapped HTTP access.
  network: "bridge"
  timeout_seconds: 60
  startup_timeout_seconds: 30
  memory: "1g"
  cpus: "1.0"
  mock_dangerous_tools: true

behavioral:
  suites:
    - dangerous_tools
    - human_approval
    - prompt_injection
    - prompt_contract
    - auth_checks
    - accuracy
    - scalability_runtime
"""
    out.write_text(content, encoding="utf-8")
    return out
