from __future__ import annotations

from pathlib import Path
from edge_agent_scanner.harness.planner import HarnessPlan


def write_evals_yaml(repo_path: Path, plan: HarnessPlan) -> Path:
    d = repo_path / ".edgeagent"
    d.mkdir(parents=True, exist_ok=True)
    out = d / "evals.yaml"

    chat_url = plan.candidate_chat_urls[0] if plan.candidate_chat_urls else "http://127.0.0.1:8000/chat"

    content = f"""# Auto-generated by Edge Agent AI. Review before running.
app:
  kind: "http"
  install_command: {repr(plan.install_command)}
  start_command: {repr(plan.start_command)}
  health_url: null
  chat_url: {repr(chat_url)}
  method: "POST"
  input_template:
    message: "{{{{prompt}}}}"
  output_path: "response"

sandbox:
  network: "limited"
  timeout_seconds: 60
  mock_dangerous_tools: true

behavioral:
  suites:
    - dangerous_tools
    - human_approval
    - prompt_injection
    - prompt_contract
    - auth_checks
    - accuracy
    - scalability_runtime
"""
    out.write_text(content, encoding="utf-8")
    return out
